[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyRetries = 5
healthcheckPath = "/api/series"
healthcheckTimeout = 300
healthcheckInterval = 30
